"""add product embeddings

Revision ID: 357cd072bb58
Revises: 1d1d3c6dd5a4
Create Date: 2026-09-14 15:23:08.769953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '357cd072bb58'
down_revision: Union[str, Sequence[str], None] = '1d1d3c6dd5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('embedding',  Vector(384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'embedding')
    # ### end Alembic commands ###
